version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: ["gunicorn", "--chdir", "deans_api", "--bind", ":8000", "deans_api.wsgi:application"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db