version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    # command: "python -c \"while True: pass\""
    entrypoint: "start_django.sh"
    env_file:
      - default.env
    volumes:
      - ./data:/data
      - ./deans_api:/work/deans-api/deans_api
    ports:
      - "8000:8000"
    depends_on:
      - db
